/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../src/utils/confidence`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/batch` | `/batch`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ui/ValueBetCard`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/prediction` | `/prediction`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leagues` | `/leagues`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../src/utils/confidence`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/batch` | `/batch`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/ui/ValueBetCard`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/prediction` | `/prediction`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/leagues` | `/leagues`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../src/utils/confidence${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/batch${`?${string}` | `#${string}` | ''}` | `/batch${`?${string}` | `#${string}` | ''}` | `/../src/components/ui/ValueBetCard${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/prediction${`?${string}` | `#${string}` | ''}` | `/prediction${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/leagues${`?${string}` | `#${string}` | ''}` | `/leagues${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../src/utils/confidence`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/batch` | `/batch`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ui/ValueBetCard`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/prediction` | `/prediction`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leagues` | `/leagues`; params?: Router.UnknownInputParams; };
    }
  }
}
